apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deploy
  template:
    metadata:
      labels:
        app: deploy
    spec:
      containers:
        - name: deploy
          image: ifilyaninitmo/itdt-contained-frontend:master
          env:
            - name:  REACT_APP_USERNAME
              value: 'SemisalovDV'
            - name:  REACT_APP_COMPANY_NAME
              value: 'ITMO'
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: deploy-service
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000
  selector:
    app: deploy