apiVersion: v1
kind: ConfigMap
metadata:
  name: lab4
  labels:
    app: lab4
data:
  react_app_username: "Semisalov Daniil"
  react_app_company_name: "ITMO"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab4
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab4
  template:
    metadata:
      labels:
        app: lab4
    spec:
      containers:
        - name: itdt-contained-frontend
          image: ifilyaninitmo/itdt-contained-frontend:master
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: lab4
                  key: react_app_username
            - name: REACT_APP_COMPANY_NAME
              valueFrom:
                configMapKeyRef:
                  name: lab4
                  key: react_app_company_name
---
apiVersion: v1
kind: Service
metadata:
  name: lab4-service
  labels:
    app: lab4
spec:
  selector:
    app: lab4
  ports:
    - protocol: TCP
      port: 8200
      targetPort: 3000
  type: LoadBalancer