apiVersion: v1
kind: Pod
metadata:
  name: vault
  namespace: default
  labels:
    app: vault
spec:
  containers:
    - name: vault
      image: vault:1.13.3
      ports:
        - containerPort: 8200
---
apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: default
  labels:
    run: vault
spec:
  ports:
    - port: 8200
      targetPort: 8200
      protocol: TCP
  selector:
    app: vault
